name: Release Build

on:
  release:
    types: [created]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      TAURI_SKIP_SIGNING: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libssl-dev \
            build-essential \
            webkit2gtk-4.1 libwebkit2gtk-4.1-dev || \
          sudo apt-get install -y webkit2gtk-4.0 libwebkit2gtk-4.0-dev

      - name: Install JS dependencies
        run: bun install

      - name: Build Tauri app
        run: bun x tauri build -y

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-bundles-${{ runner.os }}
          path: |
            src-tauri/target/release/bundle/**
            src-tauri/target/**/bundle/**
          if-no-files-found: warn
